config/routes.rb
Rails.application.routes.draw do

  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  
  # Set the root url
  root :to => 'home#home'  

end

app/models/item.rb
class Item < ActiveRecord::Base
  # List of allowable categories
  CATEGORIES = [['Boards','boards'],['Pieces','pieces'],['Clocks','clocks'],['Supplies','supplies']]
  
  # Relationships
  has_many :item_prices
  has_many :purchases

  # Scopes
  scope :alphabetical, -> { order(:name) }
  scope :active,       -> { where(active: true) }
  scope :inactive,     -> { where(active: false) }
  scope :for_category, ->(category) { where(category: category) }
  scope :for_color,    ->(color) { where("color like ?", "%#{color.downcase}%") }
  scope :need_reorder, ->{ where("reorder_level >= inventory_level") }
  
  # Validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates_numericality_of :weight, greater_than: 0
  validates_numericality_of :inventory_level, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :reorder_level, only_integer: true, greater_than_or_equal_to: 0
  validates_inclusion_of :category, in: CATEGORIES.map{|key, value| value}, message: "is not an option"
  # validates_inclusion_of :category, in: CATEGORIES.to_h.values, message: "is not an option"

  # Other methods
  def current_price
    curr = self.item_prices.current.chronological.first
    if curr.nil?
      return nil
    else
      return curr.price
    end
  end

  def price_on_date(date)
    data = self.item_prices.for_date(date).chronological.first
    if data.nil?
      return nil
    else
      return data.price
    end
  end

  def reorder?
    reorder_level >= inventory_level
  end
end

app/models/item_price.rb
class ItemPrice < ActiveRecord::Base
  # Relationships
  belongs_to :item

  # Scopes
  scope :current,       -> { where(end_date:nil) }
  scope :chronological, -> { order(start_date: :desc ) }
  scope :for_date,      ->(date) { where("start_date <= ? AND (end_date > ? OR end_date IS NULL)", date, date) }
  scope :for_item,      ->(item_id) { where(item_id: item_id) }

  # Validations
  validates_numericality_of :price, greater_than_or_equal_to: 0
  validates_date :start_date, on_or_before: lambda { Date.current }
  validates_date :end_date, on_or_after: :start_date, allow_blank: true
  validate :item_is_active_in_system

  # Callbacks
  before_create :set_end_date_of_old_price

  # Other methods
  private
  def item_is_active_in_system
    all_active_items = Item.active.all.map(&:id)
    unless all_active_items.include?(self.item_id)
      errors.add(:item_id, "is not an active item at the chess store")
    end
  end

  def set_end_date_of_old_price
    previous = ItemPrice.current.for_item(self.item_id).take
    previous.update_attribute(:end_date, self.start_date) unless previous.nil?
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  # Relationships
  belongs_to :item

  # Scopes
  scope :loss,          -> { where('quantity < 0') }
  scope :chronological, -> { order(date: :desc ) }
  scope :for_item,      ->(item_id) { where(item_id: item_id) }

  # Validations
  validates_numericality_of :quantity, only_integer: true
  validates_date :date, on_or_before: lambda { Date.current }
  validate :item_is_active_in_system

  # Callbacks
  before_create :update_item_inventory_level

  private
  def item_is_active_in_system
    all_active_items = Item.active.all.map(&:id)
    unless all_active_items.include?(self.item_id)
      errors.add(:item_id, "is not an active item at the chess store")
    end
  end

  def update_item_inventory_level
    revised_inventory = self.item.inventory_level + self.quantity
    self.item.update_attribute(:inventory_level, revised_inventory)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    # Use this to show the items that need to be reordered
    @items_to_reorder = Item.need_reorder.all.paginate(page: params[:page]).per_page(10)
  end

  def about
  end

  def contact
  end

  def privacy
  end
end

app/controllers/item_prices_controller.rb
class ItemPricesController < ApplicationController

  def index
    # Use this to show the active items and their current prices, sorted alphabetically
    @active_items = Item.active.alphabetical.paginate(page: params[:page]).per_page(10)
  end

  def new
    @item_price = ItemPrice.new
  end

  def create
    @item_price = ItemPrice.new(item_price_params)
    @item_price.start_date = Date.current
    if @item_price.save
        # if saved to database
        @item = @item_price.item
        flash[:notice] = "Changed the price of #{@item.name}."
        redirect_to item_path(@item) # go to show item page
    else
        # return to the 'new' form
        render action: 'new'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_price_params
      params.require(:item_price).permit(:item_id, :price, :start_date, :end_date)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    # Use this to show all the items broken down by category and ordered alphabetically
    @boards = Item.active.for_category('boards').alphabetical
    @pieces = Item.active.for_category('pieces').alphabetical
    @clocks = Item.active.for_category('clocks').alphabetical
    @supplies = Item.active.for_category('supplies').alphabetical
    @inactive_items = Item.inactive.alphabetical
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def show
    # need to show price history, similar items, and other details in the item show page
    @price_history = @item.item_prices.chronological.to_a
    @similar_items = Item.active.for_category(@item.category).alphabetical.select{ |i| i != @item }
  end

  def create
    @item = Item.new(item_params)
    if @item.save
        # if saved to database
        flash[:notice] = "Successfully created #{@item.name}."
        redirect_to item_path(@item) # go to show item page
    else
        # return to the 'new' form
        render action: 'new'
    end
  end

  def update
    if @item.update_attributes(item_params)
        flash[:notice] = "Successfully updated #{@item.name}."
        redirect_to @item
    else
        render action: 'edit'
    end
  end

  def destroy
    @item.destroy
    flash[:notice] = "Successfully removed #{@item.name} from the system."
    redirect_to items_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :color, :category, :weight, :inventory_level, :reorder_level, :active)
    end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    # list all the purchases in the system, ordering by date
    @purchases = Purchase.all.chronological.paginate(page: params[:page]).per_page(10)
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.date = Date.current
    if @purchase.save
        # if saved to database
        flash[:notice] = "Successfully added a purchase for #{@purchase.quantity} #{@purchase.item.name}."
        redirect_to purchases_path # go to show purchase page
    else
        # return to the 'new' form
        render action: 'new'
    end
  end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:item_id, :quantity, :date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_prices_helper.rb
module ItemPricesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/home/about.html.erb
<h3>About</h3>

<p>	<%= image_tag 'about.jpg', class: "left" %>
    We are Alex and Mark Heimann, USCF and FIDE Chess 
    Masters who have graduated from college and want
    to help you! Our goal is help you develop your 
    chess skills and provide you with the necessary
    items to do so. That's why we are committed to
    giving you the best products at the most affordable
    prices. If your school or institution needs chess items, 
    then this is the store for you! Happy shopping!
</p>

app/views/home/contact.html.erb
<h3>Contact Us</h3>

<!-- Taken from PATs example, but modified a teeny tiny bit -->
<p>	<%= image_tag 'contact.jpg', class: "left" %>Unfortunately, Alex and Mark's
    Chess Store is not a real online website, but rather a project for 
    programming students at Carnegie Mellon University. We are sure that you 
    wanted to buy some chess items from the absolute best chess players on the 
    planet, but that's how it goes sometimes. We apologize for this, and if you 
    would like to contact someone about it, here is the contact info:</p>

<!-- Contact Info -->
<i class="material-icons prefix">call</i>
(908)-838-8767 <br>
<i class="material-icons prefix">location_city</i>
5000 Forbes Avenue Pittsburgh, PA 15213 <br>
<i class="material-icons prefix">email</i>
<%= mail_to("wpchu@andrew.cmu.edu", "Winston Chu: wpchu@andrew.cmu.edu", encode: "javascript") %> 

app/views/home/home.html.erb
<h3>Welcome to the Chess Store!</h3>

<%= image_tag 'background.jpg' %>

<h4>Reorder List</h4>
	<% unless @items_to_reorder.empty? %>
		<table class="bordered highlight centered responsive-table">
			<thead>
				<tr>
					<th>Item</th>
					<th>Inventory</th>
								<th>Reorder Level</th>
					<th></th>
				</tr>
			</thead>
			
			<tbody>
				<% for item in @items_to_reorder %>
				<tr>
					<td><%= link_to item.name, item_path(item) %></td>
					<td><%= item.inventory_level %></td>
					<td><%= item.reorder_level %></td>
					<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(item) %> </a></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	<% else %>
		No items need to be reordered at this time.
	<% end %>

app/views/home/privacy.html.erb
<h3>Privacy</h3>

<!-- Taken from PATs example, but modified a teeny tiny bit -->
<p> <%= image_tag 'privacy.jpg', class: "left" %>
	Our privacy policy is simple and does not require a lawyer 
	to understand it. We will pounce on the opportunity to sell every
	bit of information on you we have at our disposal in order 
	to boost our bottom line. We will gladly sell your 
	address, phone, email, age, chess statistics, name of
	favorite superhero, color of bunny slippers you wear at 
	home, and the like, to any willing buyer who will pay us the big bucks.  
	(BTW, we <em>know</em> you wear bunny slippers at home and   
	we know what color they are.  You really have no secrets 
	from us.)  If you have sensitive information that you don't want us to 
	share with the world, then keep it to yourself -- don't tell us.  
	<br><br>
	It's really that simple.
</p>

app/views/item_prices/index.html.erb
<h3>Current Item Prices</h3>

<!-- Technically, add a new item price to the system -->
<a class="waves-effect waves-light btn" <%= link_to "Change an Item's Price", new_item_price_path %> </a>

<% unless @active_items.empty? %>
	<div class="price-table">
		<table class="bordered highlight responsive-table">
			<thead>
				<tr>
					<th>Item</th>
					<th>Price</th>
				</tr>
			</thead>

			<tbody>
				<% for item in @active_items %>
				<tr>
					<td><%= link_to item.name, item_path(item) %></td>
					<% if item.current_price.nil? %>
						<td>N/A</td>
					<% else %>
						<td><%= number_to_currency(item.current_price) %></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
<% else %>
	N/A
<% end %>

<!-- Add the pagination using will_paginate gem -->
<%= will_paginate @active_items %>

app/views/item_prices/new.html.erb
<h4><i class="medium material-icons">monetization_on</i> New Price</h4>

<div class="row">
	<%= simple_form_for(@item_price) do |f| %>

		<!-- Display error messages, if any -->
	  <% if @item_price.errors.any? %>
			<div id="error_explanation">
				<h6><%= pluralize(@item_price.errors.count, "error") %> prohibited this item from being saved:</h6>
				<% @item_price.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</div>
  	<% end %>

		<!-- Form for creating a new item price -->
		<div class="row">
			<div class="input-field col s8">
				<i class="material-icons prefix">info_outline</i>
				<%= f.label :item %><br></br>
    		<%= f.collection_select :item_id, Item.active.alphabetical.all, :id, :name %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s8">
				<i class="material-icons prefix">attach_money</i>
				<%= f.label :price %>
    		<%= f.number_field :price %>
			</div>
    </div>
		<div class ="row">
			<div class="input-field col s8">
				<button class="btn waves-effect waves-light">
					<i class="material-icons right">send</i>
					<%= f.submit %>
				</button>
			</div>
		</div>
	<% end %>
</div>

app/views/items/_boards.html.erb
<!-- Display a table showing information of all the boards -->
<table class="bordered highlight centered responsive-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Inventory</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% for item in @boards %>
		<tr>
			<td><%= link_to item.name, item_path(item) %></td>
			<% if item.current_price.nil? %>
				<td>N/A</td>
			<% else %>
				<td><%= number_to_currency(item.current_price) %></td>
			<% end %>
			<td><%= number_with_delimiter(item.inventory_level) %></td>
			<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(item) %> </a></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/items/_clocks.html.erb
<!-- Display a table showing information of all the clocks -->
<table class="bordered highlight centered responsive-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Inventory</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% for item in @clocks %>
		<tr>
			<td><%= link_to item.name, item_path(item) %></td>
			<% if item.current_price.nil? %>
				<td>N/A</td>
			<% else %>
				<td><%= number_to_currency(item.current_price) %></td>
			<% end %>
			<td><%= number_with_delimiter(item.inventory_level) %></td>
			<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(item) %> </a></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/items/_form.html.erb
<div class="row">
	<%= simple_form_for(@item) do |f| %>

		<!-- Display errors, if any -->
		<% if @item.errors.any? %>
			<div id="error_explanation">
				<h6><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h6>
				<% @item.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</div>
  	<% end %>
		
		<!-- Form for adding a new item into the system -->
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">info_outline</i>
				<%= f.label :name %>
    		<%= f.text_field :name %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">description</i>
				<%= f.label :description %>
    		<%= f.text_field :description %>
			</div>
    </div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">list</i>
				<%= f.label :category %><br></br>
				<%= f.select :category, Item::CATEGORIES %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">color_lens</i>
				<%= f.label :color %>
    		<%= f.text_field :color %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">fitness_center</i>
				<%= f.label :weight %>
    		<%= f.number_field :weight %>
			</div>
		</div>
		<!-- Only show the inventory level field if creating a new item -->
		<!-- Editing inventory level is done by making purchases -->
		<% unless @item.save %>
			<div class="row">
				<div class="input-field col s10">
					<i class="material-icons prefix">store</i>
					<%= f.label :inventory_level %>
					<%= f.number_field :inventory_level %>
				</div>
			</div>
		<% end %>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">add_shopping_cart</i>
				<%= f.label :reorder_level %>
    		<%= f.number_field :reorder_level %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<%= f.input :active, as: :boolean %>
			</div>
		</div>
		<div class ="row">
			<div class="input-field col s10">
				<button class="btn waves-effect waves-light">
					<i class="material-icons right">send</i>
					<%= f.submit %>
				</button>
			</div>
		</div>
	<% end %>
</div>

app/views/items/_inactive_items.html.erb
<!-- Display a table showing information of all the inactive items -->
<table class="bordered highlight centered responsive-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Inventory</th>
			<th>Category</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% for item in @inactive_items %>
		<tr>
			<td><%= link_to item.name, item_path(item) %></td>
			<% if item.current_price.nil? %>
				<td>N/A</td>
			<% else %>
				<td><%= number_to_currency(item.current_price) %></td>
			<% end %>
			<td><%= number_with_delimiter(item.inventory_level) %></td>
			<td><%= item.category.capitalize %></td>
			<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(item) %> </a></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/items/_pieces.html.erb
<!-- Display a table showing information of all the pieces -->
<table class="bordered highlight centered responsive-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Inventory</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% for item in @pieces %>
		<tr>
			<td><%= link_to item.name, item_path(item) %></td>
			<% if item.current_price.nil? %>
				<td>N/A</td>
			<% else %>
				<td><%= number_to_currency(item.current_price) %></td>
			<% end %>
			<td><%= number_with_delimiter(item.inventory_level) %></td>
			<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(item) %> </a></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/items/_supplies.html.erb
<!-- Display a table showing information of all the supplies -->
<table class="bordered highlight centered responsive-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Inventory</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% for item in @supplies %>
		<tr>
			<td><%= link_to item.name, item_path(item) %></td>
			<% if item.current_price.nil? %>
				<td>N/A</td>
			<% else %>
				<td><%= number_to_currency(item.current_price) %></td>
			<% end %>
			<td><%= number_with_delimiter(item.inventory_level) %></td>
			<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(item) %> </a></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/items/edit.html.erb
<h4><i class="medium material-icons">edit</i> Edit Item</h4>

<!-- Use the form for editing an item -->
<%= render partial: 'form' %>

app/views/items/index.html.erb
<!-- Flash a notice, if necessary -->
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>

<h3>Available Items </h3>
<a class="waves-effect waves-light btn" <%= link_to "Add a New Item", new_item_path %> </a>

<% unless @boards.empty? && @pieces.empty? && @clocks.empty? && @supplies.empty? && @inactive_items.empty? %>
  <!-- Show tables if items exist, otherwise display message(s) -->
  <h4>Boards</h4>
  <% unless @boards.empty? %>
    <%= render partial: "boards" %>
  <% else %>
    <p>There are no active boards in the system at this time.</p>
  <% end %>

  <h4>Pieces</h4>
  <% unless @pieces.empty? %>
    <%= render partial: "pieces" %>
  <% else %>
    <p>There are no active pieces in the system at this time.</p>
  <% end %>

  <h4>Clocks</h4>
  <% unless @clocks.empty? %>
    <%= render partial: "clocks" %>
  <% else %>
    <p>There are no active clocks in the system at this time.</p>
  <% end %>

  <h4>Supplies</h4>
  <% unless @supplies.empty? %>
    <%= render partial: "supplies" %>
  <% else %>
    <p>There are no active supplies in the system at this time.</p>
  <% end %>

  <h4>Inactive Items</h4>
  <% unless @inactive_items.empty? %>
    <%= render partial: "inactive_items" %>
  <% else %>
    <p>There are no inactive items in the system at this time.</p>
  <% end %>

<% else %>
  <p>There are no items in the system at this time.</p>
<% end %>

app/views/items/new.html.erb
<h4><i class="medium material-icons">fiber_new</i> New Item</h4>

<!-- Use the form for adding an item to the system -->
<%= render partial: 'form' %>

app/views/items/show.html.erb
<!-- Flash a notice, if necessary -->
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>

<!-- Show the details of the item -->
<h3><%= @item.name %></h3>
<p><b>Price:</b> 
	<% if @item.current_price.nil? %>
		N/A
	<% else %>
		<%= "$" + number_with_delimiter(number_with_precision(@item.current_price, precision: 2)) %>
	<% end %>
</p>
<p><b>Category:</b> <%= @item.category.capitalize %></p>
<p><b>Description:</b> <%= @item.description %></p>
<p><b>Inventory Level:</b> <%= number_with_delimiter(@item.inventory_level) %></p>
<p><b>Reorder Level:</b> <%= number_with_delimiter(@item.reorder_level) %></p>
<p><b>Color:</b> <%= @item.color %></p>
<% unless @price_history.empty? %>
	<p><b>Price History:</b></p>
		<% for p_hist in @price_history %>
			<% if p_hist.end_date.nil? %>
				<li><%= "From " + p_hist.start_date.strftime("%-m/%-d/%y") + " to today: " + number_to_currency(p_hist.price) %></li>
			<% else %>
				<li><%= "From " + p_hist.start_date.strftime("%-m/%-d/%y") + " to " + p_hist.end_date.strftime("%-m/%-d/%y") + ": " + number_to_currency(p_hist.price) %></li>
			<% end %>
		<% end %>
<% else %>
	<p>There are no prices in the system for this item at this time.
<% end %>
<p></p> <!-- Add a blank line for formatting issues -->
<% unless @similar_items.empty?%>
	<p><b>Similar Items:</b></p> 
		<% for sim_item in @similar_items %>
			<li><%= link_to sim_item.name, item_path(sim_item) %></li>
		<% end %>
<% else %>
	<p>There are no similar items in the system at this time.</p> 
<% end %>
<p></p> <!-- Add a blank line for formatting issues -->
<!-- Buttons for editing and deleting the item -->
<a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(@item) %> </a>
<a class="waves-effect waves-red btn tooltipped" data-position="top" data-delay="10" data-tooltip="Are you sure?" <%= link_to "Delete", @item, method: :delete %> </a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>A&M Chess Store :: <%= controller.controller_name.capitalize %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Materialize CSS and JavaScript links -->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <!-- Link for Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
          
  </head>

  <body>
    <!-- Nav bar goes here -->
    <nav>
      <div class="nav-wrapper teal">
        <div class="top-bar">
          <a class="brand-logo" <%= link_to "Alex & Mark's Chess Store", home_path %> </a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to "Items", items_path %></li>
            <li><%= link_to "Purchases", purchases_path %></li>
            <li><%= link_to "Prices", item_prices_path %></li>
          </ul>
        </div>
      </div>
    </nav>
  </body>
  <main>
    <div class="container">
      <div class="content">
        <div class="row">
            <!-- MAIN CONTENT GOES HERE -->
            <%= yield %>
            <%= javascript_include_tag "application" %>
        </div>
      </div>
    </div>
  </main>
  <!-- Footer goes here -->
  <%= render partial: 'partials/footer' %>  
  </body>

</html>

app/views/partials/_footer.html.erb
<footer class="page-footer teal">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="white-text">Questions, Comments, or Concerns?</h5>
				<p class="grey-text text-lighten-4">Please get in touch with the Webmaster. The email is linked below and the contact information is listed in the Contact page.</p>
				<p class="grey-text text-lighten-4"> &copy 2017 Webmaster: <a class="grey-text text-lighten-4" <%= mail_to("wpchu@andrew.cmu.edu", "Winston Chu", encode: "javascript") %> </a> </p>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="white-text">Links</h5>
				<ul>
					<div id="footer">
						<li><a class="grey-text text-lighten-3" <%= link_to 'Home', home_path %> </a></li>
						<li><a class="grey-text text-lighten-3" <%= link_to 'About', about_path %> </a></li>
						<li><a class="grey-text text-lighten-3" <%= link_to 'Contact Us', contact_path %> </a></li>
						<li><a class="grey-text text-lighten-3" <%= link_to 'Privacy Policy', privacy_path %> </a></li>
					</div>
				</ul>
			</div>
		</div>
	</div>
</footer>